language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t claytonnog/react-app -f Dockerfile.dev . 

script:
  - docker run -e CI=true claytonnog/react-app npm run test 

