language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t claytonnog/react-app -f Dockerfile.dev . 

script:
  - docker run -e CI=true claytonnog/react-app npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "clayton-neves"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




